services:
  - type: web
    name: editx-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    buildFilter:
      paths: 
        - server/**
        - orchestrator.js
        - package.json
        - render.yaml
